### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yuuyuuuy** [ZhiQiu-Kinsey/AppleLivePhotoConvert#1]
你好 合成后的小米动图，在预览界面没有声音，只有点击图片下面的动态图片进入编辑状态，播放才会有声音

**Comment by ZhiQiu-Kinsey** [comment]
感谢你报告这个问题。我已经成功解决了这个bug，现在它已经修复完毕。请你再次测试，看看是否还会出现问题。如果还有其他问题，随时告诉我。

Thank you for reporting the issue. I've successfully resolved the bug, and it has now been fixed. Please feel free to test again, and let me know if you encounter any further issues.
